export const SENSOR_TURN_ON_SUCCESS = 'SENSOR_TURN_ON_SUCCESS';
export const SENSOR_TURN_ON_ERROR = 'SENSOR_TURN_ON_ERROR';
export const SENSOR_TURN_OFF_SUCCESS = 'SENSOR_TURN_OFF_SUCCESS';
export const SENSOR_TURN_OFF_ERROR = 'SENSOR_TURN_OFF_ERROR';
export const SENSOR_GET_INFO_SUCCESS = 'SENSOR_GET_INFO_SUCCESS';
export const SENSOR_GET_INFO_ERROR = 'SENSOR_GET_INFO_ERROR';

export const SENSOR_GET_DETAIL_SUCCESS = 'SENSOR_GET_DETAIL_SUCCESS';
export const SENSOR_GET_DETAIL_ERROR = 'SENSOR_GET_DETAIL_ERROR';
export const SENSOR_GET_DETAIL_CLEAR = 'SENSOR_GET_DETAIL_CLEAR';

export const SENSOR_UPDATE_SUCCESS = 'SENSOR_UPDATE_SUCCESS';
export const SENSOR_UPDATE_ERROR = 'SENSOR_UPDATE_SUCCESS';

export const SENSOR_RESET = 'SENSOR_RESET';

export const USER_GET_INFO_SUCCESS = 'USER_GET_INFO_SUCCESS';
export const USER_GET_INFO_ERROR = 'USER_GET_INFO_ERROR';

export const SENSOR_HIGH_SUCCESS = 'SENSOR_HIGH_SUCCESS';
export const SENSOR_HIGH_ERROR = 'SENSOR_HIGH_ERROR';
export const SENSOR_MEDIUM_SUCCESS = 'SENSOR_MEDIUM_SUCCESS';
export const SENSOR_MEDIUM_ERROR = 'SENSOR_MEDIUM_ERROR';
export const SENSOR_LOW_SUCCESS = 'SENSOR_LOW_SUCCESS';
export const SENSOR_LOW_ERROR = 'SENSOR_LOW_ERROR';

export const SIGNAL_GET_INFO_SUCCESS = 'SIGNAL_GET_INFO_SUCCESS';
export const SIGNAL_HIGH_GET_INFO_SUCCESS = 'SIGNAL_HIGH_GET_INFO_SUCCESS';
export const SIGNAL_MEDIUM_GET_INFO_SUCCESS = 'SIGNAL_MEDIUM_GET_INFO_SUCCESS';
export const SIGNAL_LOW_GET_INFO_SUCCESS = 'SIGNAL_LOW_GET_INFO_SUCCESS';
export const SIGNAL_GET_INFO_ERROR = 'SIGNAL_GET_INFO_ERROR';

export const SIGNAL_X_GET_INFO_SUCCESS = 'SIGNAL_X_GET_INFO_SUCCESS';
export const SIGNAL_X_GET_INFO_ERROR = 'SIGNAL_X_GET_INFO_ERROR';

export const SIGNAL_Y_GET_INFO_SUCCESS = 'SIGNAL_Y_GET_INFO_SUCCESS';
export const SIGNAL_Y_GET_INFO_ERROR = 'SIGNAL_Y_GET_INFO_ERROR';

export const SIGNAL_GET_FORWARD_LIMIT_SWITCH_HIGH_SUCCESS =
  'SIGNAL_GET_FORWARD_LIMIT_SWITCH_HIGH_SUCCESS';
export const SIGNAL_GET_FORWARD_LIMIT_SWITCH_HIGH_FAILED =
  'SIGNAL_GET_FORWARD_LIMIT_SWITCH_HIGH_FAILED';

export const SIGNAL_GET_FORWARD_LIMIT_SWITCH_MED_SUCCESS =
  'SIGNAL_GET_FORWARD_LIMIT_SWITCH_MED_SUCCESS';
export const SIGNAL_GET_FORWARD_LIMIT_SWITCH_MED_FAILED =
  'SIGNAL_GET_FORWARD_LIMIT_SWITCH_MED_FAILED';

export const SIGNAL_GET_MOTOR_SUCCESS = 'SIGNAL_GET_MOTOR_SUCCESS';
export const SIGNAL_GET_MOTOR_FAILED = 'SIGNAL_GET_MOTOR_FAILED';

export const SIGNAL_GET_MOTOR_HIGH_FORWARD_SUCCESS =
  'SIGNAL_GET_MOTOR_HIGH_FORWARD_SUCCESS';
export const SIGNAL_GET_MOTOR_HIGH_FORWARD_FAILED =
  'SIGNAL_GET_MOTOR_HIGH_FORWARD_FAILED';

export const SIGNAL_GET_MOTOR_HIGH_REVERSE_SUCCESS =
  'SIGNAL_GET_MOTOR_HIGH_REVERSE_SUCCESS';
export const SIGNAL_GET_MOTOR_HIGH_REVERSE_FAILED =
  'SIGNAL_GET_MOTOR_HIGH_REVERSE_FAILED';

export const SIGNAL_GET_MOTOR_MED_FORWARD_SUCCESS =
  'SIGNAL_GET_MOTOR_MED_FORWARD_SUCCESS';
export const SIGNAL_GET_MOTOR_MED_FORWARD_FAILED =
  'SIGNAL_GET_MOTOR_MED_FORWARD_FAILED';

export const SIGNAL_GET_MOTOR_MED_REVERSE_SUCCESS =
  'SIGNAL_GET_MOTOR_MED_REVERSE_SUCCESS';
export const SIGNAL_GET_MOTOR_MED_REVERSE_FAILED =
  'SIGNAL_GET_MOTOR_MED_REVERSE_FAILED';

export const SIGNAL_GET_POWER_SUCCESS = 'SIGNAL_GET_POWER_SUCCESS';
export const SIGNAL_GET_POWER_FAILED = 'SIGNAL_GET_POWER_FAILED';

export const SIGNAL_GET_REVERSE_LIMIT_SWITCH_HIGH_SUCCESS =
  'SIGNAL_GET_REVERSE_LIMIT_SWITCH_HIGH_SUCCESS';
export const SIGNAL_GET_REVERSE_LIMIT_SWITCH_HIGH_FAILED =
  'SIGNAL_GET_REVERSE_LIMIT_SWITCH_HIGH_FAILED';

export const SIGNAL_GET_REVERSE_LIMIT_SWITCH_MED_SUCCESS =
  'SIGNAL_GET_REVERSE_LIMIT_SWITCH_MED_SUCCESS';
export const SIGNAL_GET_REVERSE_LIMIT_SWITCH_MED_FAILED =
  'SIGNAL_GET_REVERSE_LIMIT_SWITCH_MED_FAILED';

export const POWER_ON_SUCCESS = 'POWER_ON_SUCCESS';
export const POWER_ON_FAILED = 'POWER_ON_FAILED';

export const POWER_OFF_SUCCESS = 'POWER_OFF_SUCCESS';
export const POWER_OFF_FAILED = 'POWER_OFF_FAILED';
